"""Create file_items table

Revision ID: 001
Revises: 
Create Date: 2024-01-01 00:00:00.000000

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import sqlite

# revision identifiers, used by Alembic.
revision = '001'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('file_items',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('original_name', sa.String(length=255), nullable=False, comment='原始文件名'),
    sa.Column('stored_name', sa.String(length=255), nullable=False, comment='存储文件名'),
    sa.Column('object_path', sa.String(length=500), nullable=False, comment='MinIO对象路径'),
    sa.Column('file_size', sa.Integer(), nullable=False, comment='文件大小（字节）'),
    sa.Column('content_type', sa.String(length=100), nullable=True, comment='文件类型'),
    sa.Column('description', sa.Text(), nullable=True, comment='文件描述'),
    sa.Column('tags', sa.JSON(), nullable=True, comment='文件标签'),
    sa.Column('upload_path', sa.String(length=500), nullable=True, comment='上传路径'),
    sa.Column('creator', sa.String(length=100), nullable=True, comment='创建者'),
    sa.Column('updater', sa.String(length=100), nullable=True, comment='更新者'),
    sa.Column('is_deleted', sa.Boolean(), nullable=True, comment='是否已删除'),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=True, comment='创建时间'),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=True, comment='更新时间'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_file_items_id'), 'file_items', ['id'], unique=False)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_file_items_id'), table_name='file_items')
    op.drop_table('file_items')
    # ### end Alembic commands ###










