"""Create task_scenario_references table

Revision ID: 002
Revises: 001
Create Date: 2024-01-02 00:00:00.000000

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import sqlite

# revision identifiers, used by Alembic.
revision = '002'
down_revision = '001'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('task_scenario_references',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('task_id', sa.Integer(), nullable=False, comment='任务ID'),
    sa.Column('scenario_id', sa.Integer(), nullable=False, comment='场景ID'),
    sa.Column('is_enabled', sa.Boolean(), nullable=True, comment='是否启用'),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=True, comment='创建时间'),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=True, comment='更新时间'),
    sa.ForeignKeyConstraint(['task_id'], ['test_tasks.id'], ),
    sa.ForeignKeyConstraint(['scenario_id'], ['scenarios.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('task_id', 'scenario_id', name='uq_task_scenario')
    )
    op.create_index(op.f('ix_task_scenario_references_id'), 'task_scenario_references', ['id'], unique=False)
    op.create_index(op.f('ix_task_scenario_references_task_id'), 'task_scenario_references', ['task_id'], unique=False)
    op.create_index(op.f('ix_task_scenario_references_scenario_id'), 'task_scenario_references', ['scenario_id'], unique=False)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_task_scenario_references_scenario_id'), table_name='task_scenario_references')
    op.drop_index(op.f('ix_task_scenario_references_task_id'), table_name='task_scenario_references')
    op.drop_index(op.f('ix_task_scenario_references_id'), table_name='task_scenario_references')
    op.drop_table('task_scenario_references')
    # ### end Alembic commands ###


